AD-13664: Handle errors and logs and write in a separate Logs file
Bluescape/bluescape-cli pull request #6
Opened 2022-10-22 15:19 UTC by Rakshitha-Sheshagiri

2022-10-26 04:43 UTC, vinothkannanmani commented on src/utils/csv.ts
why need a separate file for this. why not use utlis.ts

2022-10-26 04:43 UTC, vinothkannanmani commented on src/utils/csv.ts
> +import { createObjectCsvWriter } from 'csv-writer';
we can directly write a csv file without this npm

2022-10-26 04:43 UTC, vinothkannanmani commented on src/utils/csv.ts
> +import { createObjectCsvWriter } from 'csv-writer';
if you want this one please explain here.

2022-10-26 08:10 UTC, Rakshitha-Sheshagiri commented on src/utils/csv.ts
csv.ts under utils folder already existed. So, thought of having the writeToCsvFile method here.

2022-10-26 08:54 UTC, Rakshitha-Sheshagiri commented on src/utils/csv.ts
> +import { createObjectCsvWriter } from 'csv-writer';
yes thanks, we can write to csv without the npm

2022-10-26 09:33 UTC, vinothkannanmani requested changes

2022-10-26 09:33 UTC, vinothkannanmani commented on src/commands/emailmigration/execute.ts
> +    path.resolve(__dirname, `../../../logs/email_migration_${Date.now()}`),
I think the file extension is missing if possible please attach the CSV file

2022-10-26 09:35 UTC, Rakshitha-Sheshagiri commented on src/commands/emailmigration/execute.ts
> +    path.resolve(__dirname, `../../../logs/email_migration_${Date.now()}`),
yes correct, thanks for noticing. I will include the file extension.

2022-10-26 10:16 UTC, Rakshitha-Sheshagiri commented on src/commands/emailmigration/execute.ts
> +    path.resolve(__dirname, `../../../logs/email_migration_${Date.now()}`),
[email_migration_1666774240812.csv](https://github.com/Bluescape/bluescape-cli/files/9868478/email_migration_1666774240812.csv)

2022-10-26 10:18 UTC, vinothkannanmani approved these changes
LGTM

2022-10-30 17:00 UTC, Rakshitha-Sheshagiri commented
https://jira.common.bluescape.com/browse/AD-13664

2022-11-02 12:11 UTC, prem15588 approved these changes

2022-11-02 12:11 UTC, prem15588 commented on src/commands/emailmigration/execute.ts
> +    path.resolve(__dirname, `../../../logs/email_migration_${Date.now()}.csv`),
Please add the file name we get from input + current timestamp.cs

2022-11-02 12:24 UTC, merged